
const D=window.rentalData;const NS='http://www.w3.org/2000/svg',slides=[...document.querySelectorAll('.slide')];let page=0,timer=null,selected='Luxembourg';const $=id=>document.getElementById(id);const eur=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);const notes=window.deckNotes||[
'0:00–1:00. Start with a person, not a price index: You are 27 and looking for a place of your own. This is an exploratory scenario, not a claim that all 27-year-olds have the same income or needs.',
'1:00–3:00. Explain the census snapshot. The 37.7% is 25.1 + 7.0 + 5.6 from Table 4. Do not substitute the national family-status table: its categories and denominator are not identical. Staying home does not by itself reveal constrained choice.',
'3:00–7:00. Start at 2025, €1,200 and 45 m². Raise the budget to €1,600 and then €2,000; watch the map and coverage count. Select Luxembourg, then Esch-sur-Alzette. Explain the formula and unavailable areas. Reduce the size, but stress that the rate is not specific to small flats. Restore the baseline if useful.',
'7:00–10:00. Compare endpoint maps with the same controls carried over. Read the matched-commune result below them. It removes changes in which communes are observed, not changes in the apartments advertised. Default holds purchasing power constant using annual-average Luxembourg IPCN. Read the historical nominal budget in the controls. This is not an earnings-adjusted affordability trend. The nominal toggle answers a different question.',
'10:00–12:00. Make the evidence distinction clear. National living arrangements, a rental scenario and actual access are three different measures. Hatching is not evidence that a place is cheap or expensive.',
'12:00–14:30. Schifflange: cite Table 20, 2022 data in the March 2023 report. The 246 is a stock, not availability or youth demand. Distinguish the report’s call for a stock-and-demand analysis from our proposed municipal mandate. Do not prescribe small units or shared housing before checking the evidence.',
'Appendix for discussion. Raw workbook, extraction script, harmonisation audit and notes are saved alongside the HTML. Print produces a static deck with the current scenario. Sources are clickable but the presentation itself makes no network requests.'
];
function go(i){page=Math.max(0,Math.min(slides.length-1,i));slides.forEach((s,k)=>s.classList.toggle('active',k===page));$('pageCount').textContent=`${page+1} / ${slides.length}`;$('notes').textContent=notes[page];if(timer){clearInterval(timer);timer=null;$('play').textContent='Play years'}location.hash=String(page+1)}
function toggleNotes(){$('notes').classList.toggle('open')}function full(){if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{})}
document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(page+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(page-1)}if(e.key==='Home')go(0);if(e.key.toLowerCase()==='n')toggleNotes();if(e.key.toLowerCase()==='f')full()});
function el(tag,attrs={}){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
const view=`-12 -12 ${D.vb[0]+24} ${D.vb[1]+24}`;const maps={};
function makeMap(id){const svg=$(id);svg.setAttribute('viewBox',view);const defs=el('defs'),pat=el('pattern',{id:'h'+id,width:8,height:8,patternUnits:'userSpaceOnUse',patternTransform:'rotate(45)'});pat.append(el('rect',{width:8,height:8,fill:'#d9ddd3'}),el('rect',{width:1.5,height:8,fill:'#9aa89e'}));defs.append(pat);svg.append(defs);maps[id]={};for(const [name,rings] of Object.entries(D.shapes)){const d=rings.map(r=>'M'+r.map(p=>p.join(',')).join('L')+'Z').join('');const p=el('path',{d,tabindex:id==='mainMap'?0:-1,'aria-label':name});p.dataset.name=name;svg.append(p);maps[id][name]=p;p.addEventListener('click',()=>{selected=name;$('commune').value=name;detail()});p.addEventListener('keydown',e=>{if(e.key==='Enter'){selected=name;$('commune').value=name;detail()}});p.addEventListener('pointermove',e=>{const y=svg.dataset.year;const r=D.panel[y][name];const mapSize=Number(svg.dataset.size);const mapFactor=Number(svg.dataset.factor);$('tip').textContent=name+' · '+(r.rate===null?'Unavailable':eur(r.rate*mapSize*mapFactor)+' / month'+(svg.dataset.basis==='real'?' · 2025 €':' · nominal €'));$('tip').style.display='block';$('tip').style.left=Math.min(e.clientX+14,innerWidth-280)+'px';$('tip').style.top=Math.min(e.clientY+14,innerHeight-60)+'px'});p.addEventListener('pointerleave',()=>{$('tip').style.display='none'})}for(const name of ['Luxembourg','Esch-sur-Alzette','Clervaux']){if(!D.cent[name])continue;let [x,y]=D.cent[name];let t=el('text',{x,y:y+6,'text-anchor':'middle'});t.textContent=name==='Luxembourg'?'Luxembourg City':name;svg.append(t)}}
function nominalBudget(year,budget){return $('basis').value==='real'?budget*D.cpi[year]/D.cpi['2025']:budget}
function moneyBasis(year){return $('basis').value==='real'?D.cpi['2025']/D.cpi[year]:1}
function paint(id,year,budget,size){budget=nominalBudget(year,budget);$(id).dataset.year=year;$(id).dataset.size=String(size);$(id).dataset.factor=String(moneyBasis(year));$(id).dataset.basis=$('basis').value;let within=0,available=0;for(const [name,p] of Object.entries(maps[id])){const r=D.panel[year][name];let fill=`url(#h${id})`;if(r.rate!==null){available++;if(r.rate*size<=budget){within++;fill='#147c68'}else fill='#c47a43'}p.setAttribute('fill',fill)}return{within,available}}
function detail(){const year=$('year').value,r=D.panel[year][selected],size=Number($('size').value),b=nominalBudget(year,Number($('budget').value));const body=$('detailBody');body.replaceChildren();const h=document.createElement('h3');h.textContent=selected;body.append(h);const amount=document.createElement('p');amount.className='amount';amount.textContent=r.rate===null?'Unavailable':eur(r.rate*size*moneyBasis(year));body.append(amount);const p=document.createElement('p');p.textContent=r.rate===null?(r.reason==='component unavailable'?'A predecessor commune has no published rate.':'No published rental rate in this year.'):`${$('basis').value==='real'?'Amount above in 2025 euros. ':''}${r.rate.toFixed(2)} €/m² × ${size} m² = ${eur(r.rate*size)} in ${year} euros. ${r.rate*size<=b?'Within the chosen budget.':eur((r.rate*size-b)*moneyBasis(year))+' above the chosen budget.'}`;body.append(p);const n=document.createElement('p');n.className='small rule';n.textContent=`${year} · ${r.n.toLocaleString('en-IE')} advertisements`+(r.parts.length>1?' across '+r.parts.length+' predecessor communes.':'.');body.append(n);Object.entries(maps.mainMap).forEach(([name,path])=>path.classList.toggle('selected',name===selected))}
function update(){const b=Number($('budget').value),s=Number($('size').value),y=$('year').value;$('budgetVal').textContent=eur(b);$('budgetLabel').textContent=$('basis').value==='real'?'Monthly budget · 2025 euros':'Monthly budget · nominal euros';$('sizeVal').textContent=s+' m²';$('formula').textContent=$('basis').value==='real'?`${eur(b)} in 2025 euros = ${eur(nominalBudget(y,b))} in ${y} euros. Historical threshold: ${(nominalBudget(y,b)/s).toFixed(2)} €/m².`:`Fixed nominal budget: ${eur(b)} in ${y}. Threshold: ${(b/s).toFixed(2)} €/m².`;const c=paint('mainMap',y,b,s);$('within').textContent=c.within;$('available').textContent=c.available;const a=paint('oldMap','2010',b,s),z=paint('newMap','2025',b,s);$('countOld').textContent=`${a.within} averages within · ${a.available} with data`;$('countNew').textContent=`${z.within} averages within · ${z.available} with data`;$('compareTitle').textContent=$('basis').value==='real'?'The same purchasing power. The same space.':'The same nominal euros. The same space.';$('compareSub').textContent=`${eur(b)} per month${$('basis').value==='real'?' in 2025 euros':''} · ${s} m² · 2010 budget: ${eur(nominalBudget('2010',b))}`;$('basisExplanation').textContent=($('basis').value==='real'?'IPCN-adjusted purchasing power, not income-adjusted affordability. ':'Same nominal euros, without inflation adjustment. ')+'Counts refer to communes, not dwellings, people or available listings.';const common=Object.keys(D.shapes).filter(n=>D.panel['2010'][n].rate!==null&&D.panel['2025'][n].rate!==null);const counts=['2010','2025'].map(y=>common.filter(n=>D.panel[y][n].rate*s<=nominalBudget(y,b)).length);$('balanced').textContent=`On the same ${common.length} communes observed in both years: ${counts[0]} commune averages within budget in 2010 → ${counts[1]} in 2025.`;detail()}
D.years.forEach(y=>{$('year').add(new Option(y,y))});$('year').value='2025';Object.keys(D.shapes).sort((a,b)=>a.localeCompare(b)).forEach(n=>$('commune').add(new Option(n,n)));$('commune').value=selected;['hero','mainMap','oldMap','newMap'].forEach(makeMap);paint('hero','2025',1200,45);['budget','size','year','basis'].forEach(id=>$(id).addEventListener('input',update));$('commune').addEventListener('change',()=>{selected=$('commune').value;detail()});$('reset').onclick=()=>{$('budget').value=1200;$('size').value=45;$('year').value=2025;$('basis').value='real';$('mainMap').setAttribute('viewBox',view);update()};$('zoom').onclick=()=>{const pts=D.shapes[selected].flat(),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),x=Math.min(...xs),y=Math.min(...ys),w=Math.max(...xs)-x,h=Math.max(...ys)-y;$('mainMap').setAttribute('viewBox',`${x-20} ${y-20} ${w+40} ${h+40}`)};$('unzoom').onclick=()=>$('mainMap').setAttribute('viewBox',view);$('play').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('play').textContent='Play years';return}if($('year').value==='2025')$('year').value=2009;update();$('play').textContent='Pause';timer=setInterval(()=>{let i=D.years.indexOf(Number($('year').value));if(i===D.years.length-1){clearInterval(timer);timer=null;$('play').textContent='Play years';return}$('year').value=D.years[i+1];update()},1000)};update();go(Number(location.hash.slice(1)||1)-1);
